name: Workflow CI/CD

on:
    push:
      branches:
        - main
jobs:
    test:
        name: Testing
        runs-on: ubuntu-latest
        steps:
          - 
            name: Checkout
            uses: actions/checkout@v3
          - 
            name: Set up python
            uses: actions/setup-python@v4
            with:
              python-version: '3.11'
          - 
            name: Install Poetry
            uses: snok/install-poetry@v1
            with:
                virtualenvs-in-project: true
          # - 
          #   name: Load cached venv
          #   id: cached-poetry-dependencies
          #   uses: actions/cache@v3
          #   with:
          #       path: .venv
          #       key: venv-${{ hashFiles('**/poetry.lock') }}
          - 
            name: Install dependencies
            #if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
            run: poetry install --with test --no-interaction --no-ansi -vvv
          -
            name: Run tests
            run: poetry run make testing

    lint:
        uses: ./.github/workflows/lint.yml
    
    build:
        needs: [test, lint]
        uses: ./.github/workflows/docker.yml
        secrets: inherit

    deploy:
        needs: [build]
        uses: ./.github/workflows/ecs.yml
        secrets: inherit
        