name: Workflow CI/CD

on:
    push:
      branches:
        - main
jobs:
    test:
        uses: ./.github/workflows/test.yml

    lint:
        uses: ./.github/workflows/lint.yml
    
    build:
        needs: [test, lint]
        uses: ./.github/workflows/docker.yml
        secrets: inherit
        